// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAImhni2h4YCgngxJRPCvNnQm2AMiFbdIg',
    appId: '1:433871743225:web:d9dc40896344575aebda28',
    messagingSenderId: '433871743225',
    projectId: 'refund-tracker-app',
    authDomain: 'refund-tracker-app.firebaseapp.com',
    storageBucket: 'refund-tracker-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdyhL8G7JErVL5qvZ2lIbR42uHmFsZU34',
    appId: '1:433871743225:android:50c97ea3ea9552acebda28',
    messagingSenderId: '433871743225',
    projectId: 'refund-tracker-app',
    storageBucket: 'refund-tracker-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3g0etdwRwEWuJJIlovLuJVpBuu0SiU-4',
    appId: '1:433871743225:ios:a30c24d60fd10fb2ebda28',
    messagingSenderId: '433871743225',
    projectId: 'refund-tracker-app',
    storageBucket: 'refund-tracker-app.firebasestorage.app',
    iosBundleId: 'com.example.refundTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3g0etdwRwEWuJJIlovLuJVpBuu0SiU-4',
    appId: '1:433871743225:ios:a30c24d60fd10fb2ebda28',
    messagingSenderId: '433871743225',
    projectId: 'refund-tracker-app',
    storageBucket: 'refund-tracker-app.firebasestorage.app',
    iosBundleId: 'com.example.refundTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAImhni2h4YCgngxJRPCvNnQm2AMiFbdIg',
    appId: '1:433871743225:web:e03524346f3e98e2ebda28',
    messagingSenderId: '433871743225',
    projectId: 'refund-tracker-app',
    authDomain: 'refund-tracker-app.firebaseapp.com',
    storageBucket: 'refund-tracker-app.firebasestorage.app',
  );
}
