// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWnPVYmQDVP38IVMuoZYdr3nxBMU4iiNE',
    appId: '1:397125649830:web:ae8c2a889c5d73e460bb67',
    messagingSenderId: '397125649830',
    projectId: 'axume-portal-6bfd3',
    authDomain: 'axume-portal-6bfd3.firebaseapp.com',
    storageBucket: 'axume-portal-6bfd3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBW7hamJBI14Jt14H4x_qAOw9yXY1QfHs',
    appId: '1:397125649830:android:08fa429ec5e955bd60bb67',
    messagingSenderId: '397125649830',
    projectId: 'axume-portal-6bfd3',
    storageBucket: 'axume-portal-6bfd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAviGk8WEFrtVm6LB7K3BK1H_eqT0TXJ6g',
    appId: '1:397125649830:ios:3aa5a515f9eaa0e460bb67',
    messagingSenderId: '397125649830',
    projectId: 'axume-portal-6bfd3',
    storageBucket: 'axume-portal-6bfd3.firebasestorage.app',
    iosBundleId: 'com.example.refundTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAviGk8WEFrtVm6LB7K3BK1H_eqT0TXJ6g',
    appId: '1:397125649830:ios:3aa5a515f9eaa0e460bb67',
    messagingSenderId: '397125649830',
    projectId: 'axume-portal-6bfd3',
    storageBucket: 'axume-portal-6bfd3.firebasestorage.app',
    iosBundleId: 'com.example.refundTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWnPVYmQDVP38IVMuoZYdr3nxBMU4iiNE',
    appId: '1:397125649830:web:bf7e494428d425c960bb67',
    messagingSenderId: '397125649830',
    projectId: 'axume-portal-6bfd3',
    authDomain: 'axume-portal-6bfd3.firebaseapp.com',
    storageBucket: 'axume-portal-6bfd3.firebasestorage.app',
  );

}